package constantes;

/**
 * Eumeração que define os idiomas dos produtos.
 * @author Lucas Alves Rufino e Miriane Silva Trajano do Nascimento.
 */
public enum Idioma {
	
	//fonte da pesquisa - http://pt.forvo.com/languages-codes/
	ABAZA ("Abaza"),
	ABECASIO ("Abecásio"),
	ADIGUE ("Adigue"),
	AFAR ("Afar"),
	AFRICANER ("Africâner"),
	AIMARA ("Aimara"),
	AKAN ("Akan"),
	ALBANES ("Albanês"),
	ALEMAO ("Alemão"),
	ALEUTE ("Aleúte"),
	ALTOSORABIO ("Alto Sorábio"),
	AMARICO ("Amárico"),
	ARABE ("Árabe"),
	ARAGONES ("Aragonês"),
	ARBERESHE ("Arbëreshë"),
	ARMENIO ("Armênio"),
	ASSAMES ("Assamês"),
	ASSIRIANO ("Assiriano"),
	ASTURIANO ("Asturiano"),
	AVAR ("Avar"),
	AZERI ("Azeri"),
	BALUCHI ("Balúchi"),
	BAMBARA ("Bambara"),
	BARDI ("Bardi"),
	BASCO ("Basco"),
	BASHKIR ("Bashkir"),
	BAVARO ("Bávaro"),
	BENGALI ("Bengali"),
	BIARI ("Biari"),
	BIELORUSSO ("Bielo-russo"),
	BIRMANES ("Birmanês"),
	BISLAMA ("Bislamá"),
	BOSNIO ("Bósnio"),
	BOTLIKH ("Botlikh"),
	BOUYEI ("Bouyei"),
	BRETAO ("Bretão"),
	BRIBRI ("Bribri"),
	BULGARO ("Búlgaro"),
	BURIATA ("Buriata"),
	BURUSHASKI ("Burushaski"),
	CABARDIANO ("Cabardiano"),
	CABILA ("Cabila"),
	CALMUCO ("Calmuco"),
	CAMPIDANES ("Campidanês"),
	CANARESA ("Canaresa"),
	CANTI ("Cânti"),
	CANURI ("Canúri"),
	CASSUBIA ("Cassúbia"),
	CATALAO ("Catalão"),
	CAZAQUE ("Cazaque"),
	CEBUANO ("Cebuano"),
	CENTRAL ("Central"),
	CHAMORRO ("Chamorro"),
	CHECHENO ("Checheno"),
	CHEROKEE ("Cherokee"),
	CHICHEWA ("Chichewa"),
	CHINES ("Chinês"),
	CHUANG ("Chuang"),
	CHUVACHE ("Chuvache"),
	CINGALES ("Cingalês"),
	CONCANI ("Concani"),
	CONGOLES ("Congolês"),
	COREANO ("Coreano"),
	CORNICO ("Córnico"),
	CORSICO ("Córsico"),
	CREE ("Cree"),
	CREEK ("Creek"),
	CRIOLO ("Criolo"),
	CRIOULO ("Crioulo"),
	CROATA ("Croata"),
	CUANHAMA ("Cuanhama"),
	CURDO ("Curdo"),
	DAGBANI ("Dagbani"),
	DARI ("Dari"),
	DINAMARQUES ("Dinamarquês"),
	DINCA ("Dinca"),
	DIVEHI ("Divehi"),
	DONGO ("Dongo"),
	DZONGA ("Dzonga"),
	EMILIANO ("Emiliano"),
	ERZYA ("Erzya"),
	ESCOCES ("Escocês"),
	ESLOVACO ("Eslovaco"),
	ESLOVENO ("Esloveno"),
	ESPANHOL ("Espanhol"),
	ESPERANTO ("Esperanto"),
	ESTONIANO ("Estoniano"),
	ETON ("Eton"),
	EWONDO ("Ewondo"),
	FEROES ("Feroês"),
	FIJIANO ("Fijiano"),
	FINLANDES ("Finlandês"),
	FLEMISH ("Flemish"),
	FRANCES ("Francês"),
	FRANCO ("Franco"),
	FRISAO ("Frisão"),
	FRIULANO ("Friulano"),
	FULA ("Fula"),
	GAELICO ("Gaélico"),
	GALEGOESCOCES ("Galego Escocês"),
	GALES ("Galês"),
	GEORGIANO ("Georgiano"),
	GILAKI ("Gilaki"),
	GREGO ("Grego"),
	GROENLANDES ("Groenlandês"),
	GUARANI ("Guarani"),
	GUSII ("Gusii"),
	GUZERATE ("Guzerate"),
	HAITIANO ("Haitiano"),
	HAKKA ("Hakka"),
	HASSANI ("Hassani"),
	HAUCA ("Hauçá"),
	HAVAIANO ("Havaiano"),
	HEBRAICO ("Hebraico"),
	HERERO ("Hereró"),
	HILIGAYNON ("Hiligaynon"),
	HINDI ("Hindi"),
	HIRIMOTU ("Hiri Motu"),
	HMONG ("Hmong"),
	HOLANDES ("Holandês"),
	HUNGARO ("Húngaro"),
	IBO ("Ibo"),
	IIDICHE ("Iídiche"),
	ILOCANO ("Ilocano"),
	INDONESIO ("Indonésio"),
	INGLES ("Inglês"),
	INTERLINGUA ("Interlíngua"),
	INUKTITUT ("Inuktitut"),
	INUPIAQUE ("Inupiaque"),
	IORUBA ("Ioruba"),
	IRLANDES ("Irlandês"),
	ISLANDES ("Islandês"),
	ITALIANO ("Italiano"),
	IUCATEQUE ("Iucateque"),
	IWAIDJA ("Iwaidja"),
	JAMAICANO ("Jamaicano"),
	JAPONES ("Japonês"),
	JAVANES ("Javanês"),
	JIN ("Jin"),
	KARAKALPAK ("Karakalpak"),
	KASHMIRI ("Kashmiri"),
	KHASI ("Khasi"),
	KHMER ("Khmer"),
	KIMBUNDO ("Kimbundo"),
	KINYARWANDA ("Kinyarwanda"),
	KLINGON ("Klingon"),
	KOMI ("Komi"),
	KOTAVA ("Kotava"),
	KURMANJI ("Kurmanji"),
	KUTCHI ("Kutchi"),
	LADINO ("Ladino"),
	LAK ("Lak"),
	LAKOTA ("Lakota"),
	LAOCIANA ("Laociana"),
	LATGALIO ("Latgálio"),
	LATIM ("Latim"),
	LAZ ("Laz"),
	LETAO ("Letão"),
	LEZGUI ("Lezgui"),
	LIGURIA ("Ligúria"),
	LIMBURGIO ("Limburgio"),
	LINGALA ("Lingála"),
	LINGUAINGUCHE ("Lingua Inguche"),
	LINGUANLU ("Lingua Nlu"),
	LINGUATARTARADACRIMEIA ("Língua Tártara da Crimeia"),
	LITUANO ("Lituano"),
	LOMBARDO ("Lombardo"),
	LOZI ("Lozi"),
	LUBACATANGA ("Luba-catanga"),
	LUGANDA ("Luganda"),
	LUO ("Luo"),
	LURI ("Luri"),
	LUSHOOTSEED ("Lushootseed"),
	LUXEMBURGUES ("Luxemburguês"),
	MACEDONIO ("Macedônio"),
	MAINFRANKEN ("Mainfranken"),
	MALAIALA ("Malaiala"),
	MALAIO ("Malaio"),
	MALGAXE ("Malgaxe"),
	MALTES ("Maltês"),
	MANCHU ("Manchu"),
	MANESA ("Manesa"),
	MAORI ("Maori"),
	MAPUDUNGUN ("Mapudungun"),
	MARATA ("Marata"),
	MARI ("Mari"),
	MARSHALES ("Marshalês"),
	MASBATENHO ("Masbatenho"),
	MAURITIANO ("Mauritiano"),
	MAZANDARAN ("Mazandaran"),
	MBE ("Mbe"),
	MEITEI ("Meitei"),
	MESCALERO ("Mescalero"),
	MIN ("Min"),
	MINANGKABAU ("Minangkabau"),
	MIQUEMAQUE ("Miquemaque"),
	MOHAWK ("Mohawk"),
	MOKSHA ("Moksha"),
	MONGOL ("Mongol"),
	NAPOLITANO ("Napolitano"),
	NASKAPI ("Naskapi"),
	NAUATLE ("Náuatle"),
	NAURUANO ("Nauruano"),
	NAVAJO ("Navajo"),
	NAXI ("Naxi"),
	NDEBELE ("Ndebele"),
	NEPALBHASA ("Nepal Bhasa"),
	NEPALES ("Nepalês"),
	NOGAI ("Nogai"),
	NORUEGUES ("Norueguês"),
	OCCITANICO ("Occitânico"),
	OJIBWA ("Ojibwa"),
	OKINAWAN ("Okinawan"),
	ORIYA ("Oriya"),
	OROMO ("Oromo"),
	OSAGE ("Osage"),
	OSSETIA ("Ossétia"),
	OVELHA ("Ovelha"),
	PALAUANO ("Palauano"),
	PALENQUERO ("Palenquero"),
	PALI ("Pali"),
	PANGASINAN ("Pangasinan"),
	PANJABI ("Panjabi"),
	PAPIAMENTO ("Papiamento"),
	PASHTO ("Pashto"),
	PERSA ("Persa"),
	PICARDO ("Picardo"),
	PIEMONTES ("Piemontês"),
	PITJANTJATJARA ("Pitjantjatjara"),
	POLONES ("Polonês"),
	PORTUGUES ("Português"),
	QUIATONIZAPOTECA ("Quiatoni Zapoteca"),
	QUICHUA ("Quíchua"),
	QUICUIO ("Quicuio"),
	QUIRGUIZ ("Quirguiz"),
	QUIRUNDI ("Quirundi"),
	RAPANUI ("Rapanui"),
	ROHINGYA ("Rohingya"),
	ROMAGNOL ("Romagnol"),
	ROMANCHE ("Romanche"),
	ROMANI ("Romani"),
	ROMENO ("Romeno"),
	RUKIGA ("Rukiga"),
	RUSSO ("Russo"),
	RUSYN ("Rusyn"),
	SAMIDONORTE ("Sami do norte"),
	SAMOANO ("Samoano"),
	SANGO ("Sango"),
	SANSCRITO ("Sânscrito"),
	SARDO ("Sardo"),
	SEEDIQ ("Seediq"),
	SERERE ("Serere"),
	SERVIO ("Sérvio"),
	SHONA ("Shona"),
	SHOSHONI ("Shoshoni"),
	SICILIANO ("Siciliano"),
	SILESIANO ("Silesiano"),
	SINDI ("Sindi"),
	SOMALI ("Somali"),
	SOTO ("Soto"),
	SRANAN ("Sranan"),
	SUAILI ("Suaíli"),
	SUAZI ("Suázi"),
	SUECO ("Sueco"),
	SUNDANES ("Sundanês"),
	SYLHETI ("Sylheti"),
	TADJIQUE ("Tadjique"),
	TAGALO ("Tagalo"),
	TAILANDES ("Tailandês"),
	TAITIANO ("Taitiano"),
	TAMAZIGHT ("Tamazight"),
	TAMIL ("Tâmil"),
	TARTARA ("Tártara"),
	TCHECO ("Tcheco"),
	TELUGU ("Telugu"),
	TETUM ("Tétum"),
	TIBETANO ("Tibetano"),
	TIGRINIA ("Tigrínia"),
	TLINGIT ("Tlingit"),
	TOKPISIN ("Tok Pisin"),
	TOKIPONA ("Toki Pona"),
	TONDANO ("Tondano"),
	TONGA ("Tonga"),
	TSONGA ("Tsonga"),
	TSUANA ("Tsuana"),
	TUAREGUE ("Tuaregue"),
	TUNDRANENETS ("Tundra Nenets"),
	TURCO ("Turco"),
	TURCOMANO ("Turcomano"),
	TUSCARORA ("Tuscarora"),
	TUVAN ("Tuvan"),
	TWI ("Twi"),
	UCRANIANO ("Ucraniano"),
	UDMURTO ("Udmurto"),
	UIGUR ("Uigur"),
	UOLOFE ("Uolofe"),
	URDU ("Urdu"),
	USBEQUE ("Usbeque"),
	VALAO ("Valão"),
	VENDA ("Venda"),
	VENEZIANO ("Veneziano"),
	VIETNAMITA ("Vietnamita"),
	VOLAPUQUE ("Volapuque"),
	VORO ("Võro"),
	XOSA ("Xosa"),
	YAKUT ("Yakut"),
	YEYI ("Yeyi"),
	YIDESICHUAN ("Yi de Sichuan"),
	YUPIK ("Yupik"),
	ZAZAKI ("Zazaki"),
	ZULU ("Zulu"),
	OUTROS ("Outros");
	
	private String nome;	//Nome do idioma.
	
	/**
	 * Metodo construtor para atribuição dos valores da enumeração.
	 * @param nome String - nome do idioma.
	 */
	private Idioma(String nome){
		this.nome = nome;
	}
	
	/**
	 * Metodo que retorna a representação textual do idioma
	 * @return String - nome do idioma.
	 */
	public String getNome(){
		return this.nome;
	}
	
	/**
	 * Metodo que retorna um array de String com os nomes dos idiomas da enumeracao.
	 * @return String[] - nomes dos idiomas.
	 */
	public static String[] getIdiomas(){
		Idioma[] idiomas = values();
		String[] nomes = new String[idiomas.length];		
		for(int i=0, len=idiomas.length ; i<len ; i++){	//varre o array de enumeracao.
			nomes[i] = idiomas[i].getNome();				//aplica os nomes nos array de string.
		}
		return nomes;
	}
	
	/**
	 * Metodo que recebe um numero e retorna a enumeracao respectiva a esse numero.
	 * @param number int - numero do indice de enumeraçoes
	 * @return Idioma - enumeração respectiva ao valor.
	 */
	public static Idioma seletor(int number){
		return values()[number];
	}
	
}
